WebShop/Areas/Admin/Controllers/AdminPagesController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PagedList.Core;
using WebShop.Helpper;
using WebShop.Models;

namespace WebShop.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AdminPagesController : Controller
    {
        private readonly webshopContext _context;

        public INotyfService _notifyService { get; }
        public AdminPagesController(webshopContext context, INotyfService notifyService)
        {
            _context = context;
            _notifyService = notifyService;
        }
        [Authorize]
        // GET: Admin/AdminPages
        public IActionResult Index(int? page)
        {
            var collection = _context.Pages.AsNoTracking().ToList();
            foreach (var item in collection)
            {
                if (item.CreatedDate == null)
                {
                    item.CreatedDate = DateTime.Now;
                    _context.Update(item);
                    _context.SaveChanges();
                }
            }
            var pageNumber = page == null || page <= 0 ? 1 : page.Value;
            var pageSize = 20;
            var lsPages = _context.Pages.AsNoTracking()
                
                .OrderByDescending(x => x.PageId);
            PagedList<Page> models = new PagedList<Page>(lsPages, pageNumber, pageSize);
            ViewBag.CurrentPage = pageNumber;
            return View(models);
        }

        // GET: Admin/AdminPages/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var page = await _context.Pages
                .FirstOrDefaultAsync(m => m.PageId == id);
            if (page == null)
            {
                return NotFound();
            }

            return View(page);
        }

        // GET: Admin/AdminPages/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/AdminPages/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PageId,PageName,Contents,Thumb,Published,Title,MetaDesc,MetaKey,Alias,CreatedDate,Ordering")] Page page, Microsoft.AspNetCore.Http.IFormFile fThumb)
        {
            if (ModelState.IsValid)
            {
                //Xu ly thumb
                if (fThumb != null)
                {
                    string extensiton = Path.GetExtension(fThumb.FileName);
                    string imageName = Utilities.SEOUrl(page.PageName) + extensiton;
                    page.Thumb = await Utilities.UploadFile(fThumb, @"pages", imageName.ToLower());
                }
                if (string.IsNullOrEmpty(page.Thumb)) page.Thumb = "default.jpg";
                page.Alias = Utilities.SEOUrl(page.PageName);

                _context.Add(page);
                await _context.SaveChangesAsync();
                _notifyService.Success("Thêm thành công");
                return RedirectToAction(nameof(Index));
            }
            return View(page);
        }

        // GET: Admin/AdminPages/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var page = await _context.Pages.FindAsync(id);
            if (page == null)
            {
                return NotFound();
            }
            return View(page);
        }

        // POST: Admin/AdminPages/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PageId,PageName,Contents,Thumb,Published,Title,MetaDesc,MetaKey,Alias,CreatedDate,Ordering")] Page page, Microsoft.AspNetCore.Http.IFormFile fThumb)
        {
            if (id != page.PageId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {

                    //Xu ly thumb
                    if (fThumb != null)
                    {
                        string extensiton = Path.GetExtension(fThumb.FileName);
                        string imageName = Utilities.SEOUrl(page.PageName) + extensiton;
                        page.Thumb = await Utilities.UploadFile(fThumb, @"pages", imageName.ToLower());
                    }
                    if (string.IsNullOrEmpty(page.Thumb)) page.Thumb = "default.jpg";
                    page.Alias = Utilities.SEOUrl(page.PageName);
                    _context.Update(page);

                    _notifyService.Success("Cập nhật thành công");
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PageExists(page.PageId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(page);
        }

        // GET: Admin/AdminPages/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var page = await _context.Pages
                .FirstOrDefaultAsync(m => m.PageId == id);
            if (page == null)
            {
                return NotFound();
            }

            return View(page);
        }

        // POST: Admin/AdminPages/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var page = await _context.Pages.FindAsync(id);
            _context.Pages.Remove(page);
            await _context.SaveChangesAsync();
            _notifyService.Success("Xóa thành công");
            return RedirectToAction(nameof(Index));
        }

        private bool PageExists(int id)
        {
            return _context.Pages.Any(e => e.PageId == id);
        }
    }
}

WebShop/Areas/Admin/Views/AdminPages/Create.cshtml
@model WebShop.Models.Page

@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<form asp-controller="AdminPages" asp-action="Create" method="post" enctype="multipart/form-data">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="page-header no-gutters has-tab">
        <div class="d-md-flex m-b-15 align-items-center justify-content-between">
            <div class="media align-items-center m-b-15">


            </div>
            <div class="m-b-15">
                <button class="btn btn-primary">
                    <i class="anticon anticon-save"></i>
                    <span>Save</span>
                </button>
            </div>
        </div>
        <ul class="nav nav-tabs">
            <li class="nav-item">
                <a class="nav-link active" data-toggle="tab" href="#product-edit-basic">Basic Info</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#product-edit-option">Option Info</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#product-edit-description">Description</a>
            </li>
        </ul>
    </div>
    <div class="tab-content m-t-15">
        <div class="tab-pane fade show active" id="product-edit-basic">
            <div class="card">
                <div class="card-body">
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productName">Tên page</label>
                        <input type="text" class="form-control" asp-for="PageName">
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="ShortDesc">Nội dung</label>
                        <input type="text" class="form-control" asp-for="Contents">
                    </div>
                    
                    



                    <div class="form-group">
                        <label class="font-weight-semibold" for="Thumb">Ảnh đại diện</label>
                        <input name="fThumb" type="file" class="form-control-file" asp-for="Thumb">
                        <span asp-validation-for="Thumb" class="text-danger"></span>
                    </div>
                    <div class="row">
                        <div class="m-t-25">


                        </div>
                    </div>
                    
                </div>
            </div>
        </div>
        <div class="tab-pane fade" id="product-edit-option">
            <div class="card">
                <div class="card-body">
                    
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productColors">MetaDesc</label>
                        <input type="text" class="form-control" asp-for="MetaDesc">
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productFit">Metakey</label>
                        <input type="text" class="form-control" asp-for="MetaKey">
                    </div>
                    
                </div>
            </div>
        </div>
        <div class="tab-pane fade" id="product-edit-description">
            <div class="card">
                <div class="card-body">
                    <label class="font-weight-semibold" for="productName">Mô tả</label>
                    <input type="text" class="form-control" asp-for="Title">
                </div>
            </div>
        </div>
    </div>
</form>
@section Scripts    {
    <!-- page js -->
    <script src="~/Adminassets/vendors/select2/select2.min.js"></script>
    <script src="~/Adminassets/vendors/quill/quill.min.js"></script>
    <script src="~/Adminassets/js/pages/e-commerce-product-edit.js"></script>
}

WebShop/Areas/Admin/Views/AdminPages/Delete.cshtml
@model WebShop.Models.Page

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<div class="page-header">

    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
            <a class="breadcrumb-item" asp-area="Admin" asp-controller="AdminPages" asp-action="Index">Danh sách page</a>
            <span class="breadcrumb-item active">Thông tin page: @Model.Title</span>
        </nav>
    </div>
</div>
<div class="card">
    <div class="card-body">
        <h4 class="card-title">Bạn có muốn xóa tin tức: @Model.Title</h4>
        <div class="table-responsive">
            <table class="product-info-table m-t-20">
                <tbody>
                    <tr>
                        <td>ID:</td>
                        <td class="text-dark font-weight-semibold">@Model.PageId</td>
                    </tr>
                    <tr>
                        <td>Tiêu đề:</td>
                        <td>@Model.Title</td>
                    </tr>

                    <tr>
                        <td>Mô tả:</td>
                        <td>@Model.Contents</td>
                    </tr>
                    <tr>
                        <td>Ngày tạo:</td>
                        <td>@Model.CreatedDate</td>
                    </tr>
                    <tr>
                        <td>MetaKey:</td>
                        <td>@Model.MetaKey</td>
                    </tr>
                    <tr>
                        <td>MetaDesc:</td>
                        <td>@Model.MetaDesc</td>
                    </tr>

                    @*<tr>
                    <td>Tags:</td>
                    <td>@Model.Tags</td>
                </tr>*@
                    <tr>
                        <td>Ảnh:</td>
                        <td>
                            <img width="200px" ; height="200px" src="~/images/pages/@Model.Thumb" alt="@Model.Title" />
                        </td>
                    </tr>
                    @*<tr>
                    <td>Xác nhận xóa:</td>
                    <td>
                        <form asp-controller="AdminPages" asp-action="Delete" asp-route-id="@Model.PostId">
                            <input type="hidden" asp-for="PostId" />
                            <input type="submit" value="Xác nhận xóa" class="btn btn-danger" /> |
                        </form>
                    </td>

                </tr>*@


                </tbody>

            </table>
            @*<div class="card-footer text-center">
            <form asp-action="Delete">
                <input type="hidden" asp-for="ProductId" />
                <input type="submit" value="Xác Nhận Xóa" class="btn btn-danger" /> |
            </form>

            <a asp-controller="AdminPages" asp-action="Index" class="btn btn-danger">
                <i class="fa fa-chevron-left">&nbsp;</i>Quay lại
            </a>
        </div>*@
        </div>
        <div class="card-footer text-center">
            <form asp-action="Delete">
                <input type="hidden" asp-for="PageId" />
                <input type="submit" value="Xác Nhận Xóa" class="btn btn-danger" /> |
                <a asp-controller="AdminPages" asp-action="Index" class="btn btn-danger">
                    <i class="fa fa-chevron-left">&nbsp;</i>Quay lại
                </a>
            </form>


        </div>
    </div>
</div>

WebShop/Areas/Admin/Views/AdminPages/Details.cshtml
@model WebShop.Models.Page

@{
    ViewData["Title"] = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="page-header">

    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
            <a class="breadcrumb-item" asp-area="Admin" asp-controller="AdminPages" asp-action="Index">Danh sách page</a>
            <span class="breadcrumb-item active">Thông tin sản phẩm: @Model.PageName</span>
        </nav>
    </div>
</div>
<div class="card">
    <div class="card-body">
        <h4 class="card-title">Thông tin sản phẩm: @Model.PageName</h4>
        <div class="table-responsive">
            <table class="product-info-table m-t-20">
                <tbody>
                    <tr>
                        <td>ID:</td>
                        <td class="text-dark font-weight-semibold">@Model.PageName</td>
                    </tr>
                    <tr>
                        <td>Tên page:</td>
                        <td>@Model.PageName</td>
                    </tr>
                    <tr>
                        <td>Contents:</td>
                        <td>@Model.Contents</td>
                    </tr>
                    <tr>
                        <td>Published:</td>
                        <td>@Model.Published</td>
                    </tr>
                    <tr>
                        <td>Title:</td>
                        <td>@Model.Title</td>
                    </tr>
                    
                    <tr>
                        <td>Ngày tạo:</td>
                        <td>@Model.CreatedDate</td>
                    </tr>
                    <tr>
                        <td>Ordering:</td>
                        <td>@Model.Ordering</td>
                    </tr>
                    <tr>
                        <td>Tiêu đề:</td>
                        <td>@Model.Title</td>
                    </tr>
                    <tr>
                        <td>MetaDesc:</td>
                        <td>@Model.MetaDesc</td>
                    </tr>
                    <tr>
                        <td>MetaKey:</td>
                        <td>@Model.MetaKey</td>
                    </tr>
                    
                    <tr>
                        <td>Ảnh đại diện:</td>
                        <td>
                            <img width="200px" height="200px" src="~/images/pages/@Model.Thumb" alt="@Model.Title" />
                        </td>
                    </tr>
                    
                </tbody>
            </table>
        </div>
    </div>
</div>

WebShop/Areas/Admin/Views/AdminPages/Edit.cshtml
@model WebShop.Models.Page

@{
    ViewData["Title"] = "Chỉnh sửa page" + Model.PageName;
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<form asp-controller="AdminPages" asp-action="Edit" asp-route-id="@Model.PageId" method="post" enctype="multipart/form-data">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="PageId" />
    <input type="hidden" asp-for="Thumb" />
    <div class="page-header no-gutters has-tab">
        <div class="d-md-flex m-b-15 align-items-center justify-content-between">
            <div class="media align-items-center m-b-15">


            </div>
            <div class="m-b-15">
                <button class="btn btn-primary">
                    <i class="anticon anticon-save"></i>
                    <span>Lưu thay đổi</span>
                </button>
            </div>
        </div>
        <ul class="nav nav-tabs">
            <li class="nav-item">
                <a class="nav-link active" data-toggle="tab" href="#product-edit-basic">Thông tin Page</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#product-edit-option">Thông tin SEO</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#product-edit-description">Mô tả</a>
            </li>
        </ul>
    </div>
    <div class="tab-content m-t-15">
        <div class="tab-pane fade show active" id="product-edit-basic">
            <div class="card">
                <div class="card-body">
                    <div class="form-group">
                        <label class="font-weight-semibold" for="PageName">Tên page</label>
                        <input type="text" class="form-control" asp-for="PageName">
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="Contents">Nội dung</label>
                        <input type="text" class="form-control" asp-for="Contents">
                    </div>
                    
                    



                    <div class="form-group">
                        <label class="font-weight-semibold" for="Thumb">Ảnh đại diện</label>
                        <input name="fThumb" type="file" class="form-control-file" asp-for="Thumb">
                        <span asp-validation-for="Thumb" class="text-danger"></span>
                    </div>
                    <div class="row">
                        <div class="m-t-25">


                        </div>
                    </div>

                </div>
            </div>
        </div>
        <div class="tab-pane fade" id="product-edit-option">
            <div class="card">
                <div class="card-body">

                    <div class="form-group">
                        <label class="font-weight-semibold" for="productColors">MetaDesc</label>
                        <input type="text" class="form-control" asp-for="MetaDesc">
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productFit">Metakey</label>
                        <input type="text" class="form-control" asp-for="MetaKey">
                    </div>
                    
                </div>
            </div>
        </div>
        <div class="tab-pane fade" id="product-edit-description">
            <div class="card">
                <div class="card-body">
                    <label class="font-weight-semibold" for="productName">Mô tả</label>
                    <input type="text" class="form-control" asp-for="Title">
                </div>
            </div>
        </div>
    </div>
</form>
@section Scripts    {
    <!-- page js -->
    <script src="~/Adminassets/vendors/select2/select2.min.js"></script>
    <script src="~/Adminassets/vendors/quill/quill.min.js"></script>
    <script src="~/Adminassets/js/pages/e-commerce-product-edit.js"></script>
}

WebShop/Areas/Admin/Views/AdminPages/Index.cshtml
@using PagedList.Core.Mvc;

@model PagedList.Core.IPagedList<WebShop.Models.Page>
@{
    int index = 1; 
}
@{
    int CurrentPage = ViewBag.CurrentPage;
    ViewData["Title"] = "Danh sách page" + CurrentPage;
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="page-header">

    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
            @*<a class="breadcrumb-item" asp-area="Admin" asp-controller="AdminAccounts" asp-action="Index">Danh sách tài khoản</a>*@

            <span class="breadcrumb-item active">Danh sách page: page @CurrentPage</span>
        </nav>
    </div>
</div>
<div class="card">
    <div class="card-body">
        <div class="row m-b-30">
            <div class="col-lg-8">

            </div>
            <div class="col-lg-4 text-right">
                <a class="btn btn-primary" asp-controller="AdminPages" asp-action="Create"> <i class="anticon anticon-plus-circle m-r-5"></i><span>Add Page</span></a>

            </div>
        </div>
        <div class="table-responsive">
            <table class="table table-hover e-commerce-table">
                <thead>
                    <tr>

                        <th>STTth>
                        <th>Page Name</th>

                        <th>Trạng thái</th>

                        <th>#</th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model != null)
                    {
                        foreach (var item in Model)
                        {
                            <tr>

                                <td>
                                    @index
                                </td>
                                <td>
                                    @item.PageName

                                </td>


                                <td>
                                    @if (item.Published == true)
                                    {
                                        <div class="d-flex align-items-center">
                                            <div class="badge badge-success badge-dot m-r-10"></div>
                                            <div>Public</div>
                                        </div>
                                    }
                                    else
                                    {
                                        <div class="d-flex align-items-center">
                                            <div class="badge badge-success badge-dot m-r-10"></div>
                                            <div>Non-Public</div>
                                        </div>
                                    }



                                </td>

                                <td>
                                    <a class="btn btn-primary btn-tone m-r-5" asp-area="Admin" asp-controller="AdminPages" asp-action="Details" asp-route-id="@item.PageId">View</a>
                                    <a class="btn btn-secondary btn-tone m-r-5" asp-area="Admin" asp-controller="AdminPages" asp-action="Edit" asp-route-id="@item.PageId">Edit</a>
                                    <a class="btn btn-success btn-tone m-r-5" asp-area="Admin" asp-controller="AdminPages" asp-action="Delete" asp-route-id="@item.PageId">Delete</a>
                                </td>
                            </tr>
                            index = index + 1;
                        }
                    }


                </tbody>
            </table>
            <div aria-label="Page navigation example">
                <ul class="pagination">
                    <pager class="page-container" list="@Model" options="@PagedListRenderOptions.Bootstrap4PageNumbersOnly" asp-area="Admin" asp-controller="AdminPages" asp-action="Index" />
                </ul>
            </div>
        </div>
    </div>
</div>