WebShop/Models/Supplier.cs
using System;
using System.Collections.Generic;

#nullable disable

namespace WebShop.Models
{
    public partial class Supplier
    {
        public Supplier()
        {
            Products = new HashSet<Product>();
        }

        public int SupplierId { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public int? ProductQuantity { get; set; }

        public virtual ICollection<Product> Products { get; set; }
    }
}

WebShop/Areas/Admin/Controllers/SuppliersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PagedList.Core;
using WebShop.Models;

namespace WebShop.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class SuppliersController : Controller
    {
        private readonly webshopContext _context;

        public SuppliersController(webshopContext context)
        {
            _context = context;
        }

        // GET: Admin/Suppliers
        public async Task<IActionResult> Index(int? page)
        {
            var pageNumber = page == null || page <= 0 ? 1 : page.Value;
            var pageSize = 20;
            var lsSupplier = _context.Suppliers.AsNoTracking()

                .OrderByDescending(x => x.SupplierId);
            PagedList<Supplier> models = new PagedList<Supplier>(lsSupplier, pageNumber, pageSize);
            ViewBag.CurrentPage = pageNumber;
            return View(models);
        }

        // GET: Admin/Suppliers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var supplier = await _context.Suppliers
                .FirstOrDefaultAsync(m => m.SupplierId == id);
            if (supplier == null)
            {
                return NotFound();
            }

            return View(supplier);
        }

        // GET: Admin/Suppliers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/Suppliers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("SupplierId,Name,Address,ProductQuantity")] Supplier supplier)
        {
            if (ModelState.IsValid)
            {
                _context.Add(supplier);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(supplier);
        }

        // GET: Admin/Suppliers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var supplier = await _context.Suppliers.FindAsync(id);
            if (supplier == null)
            {
                return NotFound();
            }
            return View(supplier);
        }

        // POST: Admin/Suppliers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("SupplierId,Name,Address,ProductQuantity")] Supplier supplier)
        {
            if (id != supplier.SupplierId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(supplier);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SupplierExists(supplier.SupplierId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(supplier);
        }

        // GET: Admin/Suppliers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var supplier = await _context.Suppliers
                .FirstOrDefaultAsync(m => m.SupplierId == id);
            if (supplier == null)
            {
                return NotFound();
            }

            return View(supplier);
        }

        // POST: Admin/Suppliers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var supplier = await _context.Suppliers.FindAsync(id);
            _context.Suppliers.Remove(supplier);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SupplierExists(int id)
        {
            return _context.Suppliers.Any(e => e.SupplierId == id);
        }
    }
}

WebShop/Areas/Admin/Views/Suppliers/Create.cshtml
@model WebShop.Models.Supplier

@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<form asp-controller="Suppliers" asp-action="Create" method="post" enctype="multipart/form-data">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="page-header no-gutters has-tab">
        <div class="d-md-flex m-b-15 align-items-center justify-content-between">
            <div class="media align-items-center m-b-15">
            </div>
            <div class="m-b-15">
                <button class="btn btn-primary">
                    <i class="anticon anticon-save"></i>
                    <span>Lưu</span>
                </button>
            </div>
        </div>

    </div>
    <div class="tab-content m-t-15">
        <div class="tab-pane fade show active" id="product-edit-basic">
            <div class="card">
                <div class="card-body">
                    <div class="form-group">
                        <label class="font-weight-semibold" for="Name">Tên nhà cung cấp</label>
                        <input type="text" class="form-control" asp-for="Name">
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="address">Địa chỉ</label>
                        <input type="text" class="form-control" asp-for="Address">
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="quantity">Số lượng hàng</label>
                        <input type="number" class="form-control" asp-for="ProductQuantity" />
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
<div>
    <a class="btn btn-primary btn-tone m-r-5" asp-action="Index">Quay lại</a>
</div>

WebShop/Areas/Admin/Views/Suppliers/Delete.cshtml
@model WebShop.Models.Supplier

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<div class="page-header">

    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
            <a class="breadcrumb-item" asp-area="Admin" asp-controller="Suppliers" asp-action="Index">Danh sách nhà cung cấp</a>
            <span class="breadcrumb-item active">Thông tin nhà cung cấp: @Model.Name</span>
        </nav>
    </div>
</div>
<div class="card">
    <div class="card-body">
        <h4 class="card-title">Bạn có muốn xóa nhà cung cấp: @Model.Name</h4>
        <div class="table-responsive">
            <table class="product-info-table m-t-20">
                <tbody>
                    <tr>
                        <td>ID:</td>
                        <td class="text-dark font-weight-semibold">@Model.SupplierId</td>
                    </tr>
                    <tr>
                        <td>Tên nhà cung cấp:</td>
                        <td>@Model.Name</td>
                    </tr>
                    <tr>
                        <td>Địa Chỉ:</td>
                        <td>@Model.Address</td>
                    </tr>
                    <tr>
                        <td>Số lượng hàng cung cấp:</td>
                        <td>@Model.ProductQuantity</td>
                    </tr>
                    <tr>
                        <td>Xác nhận xóa:</td>
                        <td>
                            <form asp-controller="AdminCategories" asp-action="Delete" asp-route-id="@Model.SupplierId">
                                <input type="hidden" asp-for="SupplierId" />
                                <input type="submit" value="Xác nhận xóa" class="btn btn-danger" />
                            </form>
                        </td>
                    </tr>
                </tbody>
            </table>
            @*<div class="card-footer text-center">
            <form asp-action="Delete">
            <input type="hidden" asp-for="ProductId" />
            <input type="submit" value="Xác Nhận Xóa" class="btn btn-danger" /> |
            </form>

            <a asp-controller="AdminProducts" asp-action="Index" class="btn btn-danger">
            <i class="fa fa-chevron-left">&nbsp;</i>Quay lại
            </a>
            </div>*@
        </div>
    </div>
</div>
<div>
    <a class="btn btn-primary btn-tone m-r-5" asp-action="Index">Quay lại</a>
</div>

WebShop/Areas/Admin/Views/Suppliers/Details.cshtml
@model WebShop.Models.Supplier

@{
    ViewData["Title"] = "Chỉnh sửa Nhà Cung Cấp" + Model.Name;
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<div class="page-header">

    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
            <a class="breadcrumb-item" asp-area="Admin" asp-controller="Suppliers" asp-action="Index">Danh sách nhà cung cấp</a>
            <span class="breadcrumb-item active">Thông tin nhà cung cấp: @Model.Name</span>
        </nav>
    </div>
</div>
<div class="card">
    <div class="card-body">
        <h4 class="card-title">Thông tin nhà cung cấp: @Model.Name</h4>
        <div class="table-responsive">
            <table class="product-info-table m-t-20">
                <tbody>
                    <tr>
                        <td>ID:</td>
                        <td class="text-dark font-weight-semibold">@Model.SupplierId</td>
                    </tr>
                    <tr>
                        <td>Tên nhà cung cấp:</td>
                        <td>@Model.Name</td>
                    </tr>
                    <tr>
                        <td>Địa chỉ:</td>
                        <td>@Model.Address</td>
                    </tr>
                    <tr>
                        <td>Số lượng hàng cung cấp:</td>
                        <td>@Model.ProductQuantity</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
<div>
    <a class="btn btn-primary btn-tone m-r-5" asp-action="Index">Quay lại</a>
</div>

WebShop/Areas/Admin/Views/Suppliers/Edit.cshtml
@model WebShop.Models.Supplier

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>Chỉnh Sửa</h1>

<h4>Nhà Cung Cấp</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="SupplierId" />
            <div class="form-group">
                <label asp-for="Name" class="control-label">Tên nhà cung cấp</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label">Địa chỉ</label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductQuantity" class="control-label">Số lượng hàng cung cấp</label>
                <input asp-for="ProductQuantity" class="form-control" />
                <span asp-validation-for="ProductQuantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Lưu" class="btn btn-primary" />
                
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-primary btn-tone m-r-5" asp-action="Index">Quay lại</a>
</div>

WebShop/Areas/Admin/Views/Suppliers/Index.cshtml
@using PagedList.Core.Mvc;
@model PagedList.Core.IPagedList<WebShop.Models.Supplier>
@{
    int index = 1;
}
@{
    int CurrentPage = ViewBag.CurrentPage;
    ViewData["Title"] = "Danh sách nhà cung cấp" + CurrentPage;
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<div class="page-header">

    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
            @*<a class="breadcrumb-item" asp-area="Admin" asp-controller="AdminAccounts" asp-action="Index">Danh sách tài khoản</a>*@

            <span class="breadcrumb-item active">Danh sách nhà cung cấp: trang @CurrentPage</span>
        </nav>
    </div>
</div>
<div class="card">
    <div class="card-body">
        <div class="row m-b-30">
            <div class="col-lg-8">
            </div>
            <div class="col-lg-4 text-right">
                <a class="btn btn-primary" asp-controller="Suppliers" asp-action="Create"> <i class="anticon anticon-plus-circle m-r-5"></i><span>Thêm</span></a>

            </div>
        </div>
        <div class="table-responsive">
            <table class="table table-hover e-commerce-table">
                <thead>
                    <tr>
                        <th>STT</th>

                        <th>Tên nhà cung cấp</th>

                        <th>Địa chỉ</th>

                        <th>Số lượng hàng cung cấp</th>

                        <th>Thao tác</th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model != null)
                    {
                        foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @index
                                </td>
                                <td>
                                    @item.Name

                                </td>
                                <td>
                                    @item.Address

                                </td>
                                <td>
                                    @item.ProductQuantity

                                </td>
                                <td>
                                    <a class="btn btn-primary btn-tone m-r-5" asp-area="Admin" asp-controller="Suppliers" asp-action="Details" asp-route-id="@item.SupplierId">Xem</a>
                                    <a class="btn btn-secondary btn-tone m-r-5" asp-area="Admin" asp-controller="Suppliers" asp-action="Edit" asp-route-id="@item.SupplierId">Sửa</a>
                                    <a class="btn btn-success btn-tone m-r-5" asp-area="Admin" asp-controller="Suppliers" asp-action="Delete" asp-route-id="@item.SupplierId">Xóa</a>
                                </td>
                            </tr>
                            index = index + 1;
                        }
                    }
                </tbody>
            </table>
            <div aria-label="Page navigation example">
                <ul class="pagination">
                    <pager class="page-container" list="@Model" options="@PagedListRenderOptions.Bootstrap4PageNumbersOnly" asp-area="Admin" asp-controller="Suppliers" asp-action="Index" />
                </ul>
            </div>
        </div>
    </div>
</div>