WebShop/Areas/Admin/Controllers/AdminCustomersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PagedList.Core;
using WebShop.Models;

namespace WebShop.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AdminCustomersController : Controller
    {
        private readonly webshopContext _context;

        public AdminCustomersController(webshopContext context)
        {
            _context = context;
        }
        [Authorize]
        // GET: Admin/AdminCustomers
        public IActionResult Index(int? page)
        {
            var pageNumber = page == null || page <= 0 ? 1 : page.Value;
            var pageSize = 20;
            var lsCustomers = _context.Customers.AsNoTracking()
                .Include(x => x.Location)
                .OrderByDescending(x => x.CreateDate);
            PagedList<Customer> models = new PagedList<Customer>(lsCustomers, pageNumber, pageSize);
            ViewBag.CurrentPage = pageNumber;
            return View(models);
        }

        // GET: Admin/AdminCustomers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customer = await _context.Customers
                .FirstOrDefaultAsync(m => m.CustomerId == id);
            if (customer == null)
            {
                return NotFound();
            }

            return View(customer);
        }

        // GET: Admin/AdminCustomers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/AdminCustomers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CustomerId,FullName,Birthday,Avatar,Address,Email,Phone,LocationId,District,Ward,CreateDate,Password,Salt,LastLogin,Active")] Customer customer)
        {
            if (ModelState.IsValid)
            {
                _context.Add(customer);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(customer);
        }

        // GET: Admin/AdminCustomers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customer = await _context.Customers.FindAsync(id);
            if (customer == null)
            {
                return NotFound();
            }
            return View(customer);
        }

        // POST: Admin/AdminCustomers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CustomerId,FullName,Birthday,Avatar,Address,Email,Phone,LocationId,District,Ward,CreateDate,Password,Salt,LastLogin,Active")] Customer customer)
        {
            if (id != customer.CustomerId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(customer);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CustomerExists(customer.CustomerId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(customer);
        }

        // GET: Admin/AdminCustomers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customer = await _context.Customers
                .FirstOrDefaultAsync(m => m.CustomerId == id);
            if (customer == null)
            {
                return NotFound();
            }

            return View(customer);
        }

        // POST: Admin/AdminCustomers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var customer = await _context.Customers.FindAsync(id);
            _context.Customers.Remove(customer);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CustomerExists(int id)
        {
            return _context.Customers.Any(e => e.CustomerId == id);
        }
    }
}

WebShop/Areas/Admin/Views/AdminCustomers/Create.cshtml
@model WebShop.Models.Customer

@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>Create</h1>

<h4>Customer</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FullName" class="control-label"></label>
                <input asp-for="FullName" class="form-control" />
                <span asp-validation-for="FullName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Birthday" class="control-label"></label>
                <input asp-for="Birthday" class="form-control" />
                <span asp-validation-for="Birthday" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Avatar" class="control-label"></label>
                <input asp-for="Avatar" class="form-control" />
                <span asp-validation-for="Avatar" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LocationId" class="control-label"></label>
                <input asp-for="LocationId" class="form-control" />
                <span asp-validation-for="LocationId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="District" class="control-label"></label>
                <input asp-for="District" class="form-control" />
                <span asp-validation-for="District" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ward" class="control-label"></label>
                <input asp-for="Ward" class="form-control" />
                <span asp-validation-for="Ward" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreateDate" class="control-label"></label>
                <input asp-for="CreateDate" class="form-control" />
                <span asp-validation-for="CreateDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Salt" class="control-label"></label>
                <input asp-for="Salt" class="form-control" />
                <span asp-validation-for="Salt" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastLogin" class="control-label"></label>
                <input asp-for="LastLogin" class="form-control" />
                <span asp-validation-for="LastLogin" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Active" class="control-label"></label>
                <input asp-for="Active" class="form-control" />
                <span asp-validation-for="Active" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

WebShop/Areas/Admin/Views/AdminCustomers/Delete.cshtml
@model WebShop.Models.Customer

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<div class="page-header">

    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
            <a class="breadcrumb-item" asp-area="Admin" asp-controller="AdminCategories" asp-action="Index">Danh sách loại sản phẩm</a>
            <span class="breadcrumb-item active">Thông tin khách hàng: @Model.FullName</span>
        </nav>
    </div>
</div>
<div class="card">
    <div class="card-body">
        <h4 class="card-title">Bạn có muốn xóa khách hàng: @Model.FullName</h4>
        <div class="table-responsive">
            <table class="product-info-table m-t-20">
                <tbody>
                    <tr>
                        <td>ID:</td>
                        <td class="text-dark font-weight-semibold">@Model.CustomerId</td>
                    </tr>
                    <tr>
                        <td>Tên khách hàng:</td>
                        <td>@Model.FullName</td>
                    </tr>
                    
                    <tr>
                        <td>Địa chỉ:</td>
                        <td>@Model.Address</td>
                    </tr>
                    <tr>
                        <td>Email:</td>
                        <td>@Model.Email</td>
                    </tr>
                    <tr>
                        <td>SĐT:</td>
                        <td>@Model.Phone</td>
                    <tr>
                        <td>Ngày tạo:</td>
                        <td>@Model.CreateDate</td>
                    </tr>
                    
                    
                    <tr>
                        <td>Xác nhận xóa:</td>
                        <td>
                            <form asp-controller="AdminCategories" asp-action="Delete" asp-route-id="@Model.CustomerId">
                                <input type="hidden" asp-for="CustomerId" />
                                <input type="submit" value="Xác nhận xóa" class="btn btn-danger" /> |

                            </form>

                        </td>


                    </tr>


                </tbody>
            </table>
            @*<div class="card-footer text-center">
                    <form asp-action="Delete">
                        <input type="hidden" asp-for="ProductId" />
                        <input type="submit" value="Xác Nhận Xóa" class="btn btn-danger" /> |
                    </form>

                    <a asp-controller="AdminProducts" asp-action="Index" class="btn btn-danger">
                        <i class="fa fa-chevron-left">&nbsp;</i>Quay lại
                    </a>
                </div>*@
        </div>
    </div>
</div>

WebShop/Areas/Admin/Views/AdminCustomers/Details.cshtml
@model WebShop.Models.Customer

@{
    ViewData["Title"] = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<div class="page-header">

    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
            <a class="breadcrumb-item" asp-area="Admin" asp-controller="AdminCustomers" asp-action="Index">Danh sách khách hàng</a>
            <span class="breadcrumb-item active">Thông tin khách hàng: @Model.FullName</span>
        </nav>
    </div>
</div>
<div class="card">
    <div class="card-body">
        <h4 class="card-title">Thông tin khách hàng: @Model.FullName</h4>
        <div class="table-responsive">
            <table class="product-info-table m-t-20">
                <tbody>
                    <tr>
                        <td>ID:</td>
                        <td class="text-dark font-weight-semibold">@Model.CustomerId</td>
                    </tr>
                    <tr>
                        <td>Tên khách hàng:</td>
                        <td>@Model.FullName</td>
                    </tr>

                    <tr>
                        <td>Địa chỉ:</td>
                        <td>@Model.Address</td>
                    </tr>
                    <tr>
                        <td>Email:</td>
                        <td>@Model.Email</td>
                    </tr>
                    <tr>
                        <td>SĐT:</td>
                        <td>@Model.Phone</td>
                    <tr>
                        <td>Ngày tạo:</td>
                        <td>@Model.CreateDate</td>
                    </tr>


                </tbody>
            </table>
        </div>
    </div>
</div>

WebShop/Areas/Admin/Views/AdminCustomers/Edit.cshtml
@model WebShop.Models.Customer

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<form asp-controller="AdminCustomers" asp-action="Edit" asp-route-id="@Model.CustomerId" method="post" enctype="multipart/form-data">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="CustomerId" />
    

    <div class="page-header no-gutters has-tab">
        <div class="d-md-flex m-b-15 align-items-center justify-content-between">
            <div class="media align-items-center m-b-15">


            </div>
            <div class="m-b-15">
                <button class="btn btn-primary">
                    <i class="anticon anticon-save"></i>
                    <span>Save</span>
                </button>
            </div>
        </div>

    </div>
    <div class="tab-content m-t-15">
        <div class="tab-pane fade show active" id="product-edit-basic">
            <div class="card">
                <div class="card-body">
                    <div class="form-group">
                        <label class="font-weight-semibold" for="FullName">Tên khách hàng</label>
                        <input type="text" class="form-control" asp-for="FullName">
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="Address">Địa chỉ</label>
                        <input type="text" class="form-control" asp-for="Address">
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="Email">Email</label>
                        <input type="text" class="form-control" asp-for="Email">
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="Phone">SĐT</label>
                        <input type="text" class="form-control" asp-for="Phone">
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="CreateDate">Ngày tạo</label>
                        <input type="text" class="form-control" asp-for="CreateDate">
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

WebShop/Areas/Admin/Views/AdminCustomers/Index.cshtml
@using PagedList.Core.Mvc;

@model PagedList.Core.IPagedList<WebShop.Models.Customer>
@{
    int index = 1; 
    }
@{
    int CurrentPage = ViewBag.CurrentPage;
    ViewData["Title"] = "Danh sách khách hàng" + CurrentPage;
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="page-header">

    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
            @*<a class="breadcrumb-item" asp-area="Admin" asp-controller="AdminAccounts" asp-action="Index">Danh sách tài khoản</a>*@

            <span class="breadcrumb-item active">Danh sách khách hàng: page @CurrentPage</span>
        </nav>
    </div>
</div>
<div class="card">
    <div class="card-body">
        <div class="row m-b-30">
            <div class="col-lg-12">
                
            </div>

        </div>
        <div class="table-responsive">
            <table class="table table-hover e-commerce-table">
                <thead>
                    <tr>

                        <th>STT</th>
                        <th>Họ và tên</th>

                        <th>Địa chỉ</th>
                        <th>Chức năng</th>
                   
                    </tr>
                </thead>
                <tbody>
                    @if (Model != null)
                    {
                        foreach (var item in Model)
                        {
                            <tr>

                                <td>
                                    @index
                                </td>
                                <td>
                                    <p>@item.FullName</p>
                                    <p>@item.Phone</p>
                                    <p>@item.Email</p>
                                </td>


                                <td>@item.Address</td>
                                @*<td>@item.Location.Name</td>*@
                                <td>
                                    <a class="btn btn-primary btn-tone m-r-5" asp-area="Admin" asp-controller="AdminCustomers" asp-action="Details" asp-route-id="@item.CustomerId">View</a>
                                    <a class="btn btn-secondary btn-tone m-r-5" asp-area="Admin" asp-controller="AdminCustomers" asp-action="Edit" asp-route-id="@item.CustomerId">Edit</a>
                                    <a class="btn btn-success btn-tone m-r-5" asp-area="Admin" asp-controller="AdminCustomers" asp-action="Delete" asp-route-id="@item.CustomerId">Delete</a>
                                </td>
                            </tr>
                            index = index + 1;
                        }
                    }


                </tbody>
            </table>
            <div aria-label="Page navigation example">
                <ul class="pagination">
                    <pager class="page-container" list="@Model" options="@PagedListRenderOptions.Bootstrap4PageNumbersOnly" asp-area="Admin" asp-controller="AdminCustomers" asp-action="Index" />
                </ul>
            </div>
        </div>
    </div>
</div>